### ISSUE TITLE
How to get and use the node features of the syn-cora dataset?

### ISSUE THREAD

**Issue by LirongWu** [GemsLab/H2GCN#5]
Recently I had the pleasure of reading your paper "Beyond Homophily in Graph Neural Networks: Current Limitations and Effective Designs" published in NIPS and was impressed with the algorithm and experimental results. I am following the instructions on your github to try to reproduce your experiment using the H2GCN algorithm alone (instead of signac). I downloaded the synthetic dataset using the "get-syn-cora.sh" script file you provided, but during the experiment I noticed that the downloaded ".allx" file does not seem to contain the node features. (The data in ".allx" are some sparse, binary-valued matrices, although the format is ture.) Therefore, I would like to check with you: Does the downloaded dataset named "workspace" already include node features? If yes, how do I use it? Is it possible to call it directly using the same interface as Kipf?  If not, how should I regenerate the features to be able to reproduce the results reported in Figure2(a)? Could you please provide it in the same as Kipf et.al, I believe it would be very profitable for the community and to promote your work. We sincerely look forward to hearing from you!

**Comment by jiong-zhu** [comment]
Hi Lirong, thank you for your interest in our work! 

- Yes, the downloaded dataset should include everything you need to run the experiments, including node features. The `.allx` files we provided should be in the same format as the ones provided by Kipf et al.
- On the level of train-validation-test splits (e.g. `workspace/bfd0ae58a3c870b860ab42382ac416c2/features/313255294c48f167af526a058ba65d62/splits/33cffc3d560873eb6d85e2640d956fd4/`), the files are already organized using mostly the same format as [Planetoid](https://github.com/kimiyoung/planetoid) and Kipf et al. 
- However, if you want to directly use the dataset code provided by Kipf et al., you should include the corresponding change as in the [Line 188 of this file](https://github.com/GemsLab/H2GCN/blob/6e42eec34d854c1adf9e01c2c26985d03262d9bc/experiments/h2gcn/utils/dataset.py#L188) on their code, otherwise you may not get correct results on the synthetic graphs without correct sorting of the node ID. A more recommended way is to use our dataset code, which is compatible to the one provided by Kipf et al. (See [Line 67-68 here for an example](https://github.com/GemsLab/H2GCN/blob/6e42eec34d854c1adf9e01c2c26985d03262d9bc/baselines/gcn/gcn/train.py#L67))

**Comment by LirongWu** [comment]
Thank you very much for your patient answer, which solved my problem.
